### ISSUE TITLE
Creation of technical documentation

### ISSUE THREAD

**Issue by izzyStewart** [nestauk/cci_nepal#25]
**Tasks**
- [ ]  Produce outline of report with headers and bullets of what goes in each section
- [ ] Produce a list of visualisations we need to produce for the report

**Comment by izzyStewart** [comment]
**Tasks**
- [ ]  Produce outline of report with headers and bullets of what goes in each section
- [ ] Produce a list of visualisations we need to produce for the report
